name: Org Release

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  create-release:
    uses: AndyMills-CloudBeard/Actions/.github/workflows/org-release.yml@4f913ac5aff74fe98d6121e6e979955927f99a48 # v1.0.0
    permissions:
      contents: write
      pull-requests: write
